iknsa_comment:
    resource: "@IKNSACommentBundle/Resources/config/routing.yml"
    prefix:   /

iknsa_post:
    resource: "@IKNSAPostBundle/Resources/config/routing.yml"
    prefix:   /

iknsa_blog:
    resource: "@IKNSABlogBundle/Resources/config/routing.yml"
    prefix:   /

iknsa_app:
    resource: "@IKNSAAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

